from tkinter import *
from tkinter import messagebox
a=Tk()
a.title("Student-Registration")
a.configure(bg="red")
l1=Label(a,text="STUDENT-REGISTRATION",font=("Arial bold",15),bg="red")
l1.grid(column=1,row=1)
l2=Label(a,text="Name",font=("Arial bold",15),bg="red")
l2.grid(column=0,row=2)
l3=Label(a,text="Email",font=("Arial bold",15),bg="red")
l3.grid(column=0,row=3)
l4=Label(a,text="Phone  no",font=("Arial bold",15),bg="red")
l4.grid(column=0,row=4)
e1=Entry(a,width=15)
e1.grid(column=1,row=2)
e2=Entry(a,width=15)
e2.grid(column=1,row=3)
e3=Entry(a,width=15)
e3.grid(column=1,row=4)
l5=Label(a,text="Gender",font=("Arial bold",15),bg="red")
l5.grid(column=0,row=5)
var=IntVar()
r1=Radiobutton(a,text="Male",variable=var,value=1,bg="red")
r1.grid(column=1,row=5)
r2=Radiobutton(a,text="Female",variable=var,value=0,bg="red")
r2.grid(column=2,row=5)
def hello():
    name=e1.get()
    messagebox.showinfo("","Hello "+name+" Your  reg done!")
b=Button(a,text="Submit",command=hello)
b.grid(column=1,row=6)
a.mainloop()
